[program:artisan-seo-scheduler]
process_name=%(program_name)s
directory=/var/www/artisan-seo/current
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/artisan-seo-scheduler.log
stopwaitsecs=3600
